# Ejercitación: Procesamiento de datos con R

**Bibliotecas utilizadas**

```{r}
library('dplyr')
library('tidyr')
library('readxl')
library('stringr')
```

**Import**

```{r}
harberstonData <- read_xlsx("../Syrah 2016 (Monterey) Stem additions.xlsx",1)
fullScanData <- read_xlsx("../Syrah 2016 (Monterey) Stem additions.xlsx",2)
```

**Tidy**

```{r}
harberstonData <- harberstonData %>% mutate(`Sample ID` = sub(" \\+ ", " ", toupper(`Sample ID`)))

colsFSData <- colnames(fullScanData)
newColsFSData <- c()

i <- 1
while (i<=ncol(fullScanData)){
  if (i%%2==0){
    
    newColsFSData[i] <- colsFSData[i-1]
    
  } else {
    if (i==1){
      newColsFSData[1] <- fullScanData[1,1]
    } else {
      newColsFSData[i] <- 'del'  
    }
  }
  i <- i+1
}

fullScanData <- fullScanData[-1,]
colnames(fullScanData) <- newColsFSData
fullScanData <- na.omit(fullScanData)

tidyFullScanData <- fullScanData %>% select(!starts_with('del')) %>% pivot_longer(!`Wavelength (nm)`, names_to = 'Sample ID', values_to = 'Abs') %>% pivot_wider(names_from = `Wavelength (nm)`, values_from = 'Abs') %>% mutate(`Sample ID` = sub("MW3", "MW 3",sub("100 %", "100%", `Sample ID`)))

stemsData <- left_join(harberstonData,tidyFullScanData,by="Sample ID")
```

**Guardar .csv resultante**

```{r}
write.csv(stemsData, "../Resultado - Syrah Monterey Stems (2016).csv")
```
